spring:
  application:
    name: cinema-backend
  datasource:
    url: jdbc:mysql://localhost:3306/cinema
    username: cinema_user
    password: cinema_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true