spring:
  application:
    name: library-explorer
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: library_user
    password: library_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true